package:
  name: ilastikrag
  version: "0.1"

source:
  git_url: ../
  git_tag: HEAD

build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - python 2.7*

  run:
    - python 2.7*
    - numpy  >=1.9
    - hdf5   1.8.14
    - h5py   >=2.5
    - pandas >=0.16
    - vigra  1.11rc*
    - networkx >=1.11

test:
  requires:
    - nose  >=1.3
  
  imports:
    - ilastikrag

about:
  home: https://github.com/stuarteberg/ilastikrag
  license: Simplified BSD
  license_file: LICENSE-BSD
  summary: ND Region Adjacency Graph with edge feature algorithms
